# The overall format is standard TOML format, v0.5.0.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
    issueTrackerURL="https://github.com/yooksi/cocolib/issues"
    modId="cocolib"
    version="${version}"
    displayName="CocoLib"
    displayURL="https://github.com/yooksi/cocolib"
    credits="Thanks to Java and Forge team"
    authors="yooksi"
    description='''Simple Minecraft modding library.'''

[[dependencies.cocolib]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cocolib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
